#!/usr/bin/env groovy

pipeline {
  agent any

  stages {

    stage('Terraform Init') {
      agent {
        docker {
          reuseNode true
          image 'terraform-az'
          args '-v /var/run/docker.sock'
        }
      }
      steps {
        sh (script:"cd env/pay && terraform planinit -input=false")
      }
    }
    stage('Terraform Plan') {
      agent {
        docker {
          reuseNode true
          image 'terraform-az'
          args '-v /var/run/docker.sock'
        }
      }
      steps {
          withCredentials([azureServicePrincipal('SimonTestSPN')]) {
            sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
            sh (script:"cd env/pay && terraform plan -input=false")
      }
     }
    }
  }
  post { 
    cleanup { 
      deleteDir()
    }
  }
}
